### ISSUE TITLE
Doesn't like 32bit wavs, rendered with Sox

### ISSUE THREAD

**Issue by mungewell** [git-moss/ConvertWithMoss#3]
Rendered some files with Sox whilst debuging root note issue, these cause lots (!!) of warning messages.
```
Detecting and converting multisamples...

Analyzing: C:\Users\simon\Documents\MPC\20211014_keygroup_exp_[ProjectData]\sources\71264_v2_BanjoUkulele_DaveHilowitz_SFZ\Banjo Ukulele [SFZ]\silent

Analyzing: C:\Users\simon\Documents\MPC\20211014_keygroup_exp_[ProjectData]\sources\71264_v2_BanjoUkulele_DaveHilowitz_SFZ\Banjo Ukulele [SFZ]\silent\Samples

Analyzing: C:\Users\simon\Documents\MPC\20211014_keygroup_exp_[ProjectData]\sources\71264_v2_BanjoUkulele_DaveHilowitz_SFZ\Banjo Ukulele [SFZ]\silent\Banjo Ukulele.sfz
Can't read sample file. Either not a WAV or broken: %1

java.io.IOException: de.mossgrabers.sampleconverter.exception.CompressionNotSupportedException: Unsupported data compression: Extensible

at de.mossgrabers.sampleconverter.core.DefaultSampleMetadata.addMissingInfoFromWaveFile(DefaultSampleMetadata.java:538)

at de.mossgrabers.sampleconverter.core.detector.AbstractDetectorTask.loadMissingValues(AbstractDetectorTask.java:292)

at de.mossgrabers.sampleconverter.format.sfz.SfzDetectorTask.parseVelocityLayers(SfzDetectorTask.java:204)

at de.mossgrabers.sampleconverter.format.sfz.SfzDetectorTask.parseMetadataFile(SfzDetectorTask.java:114)

at de.mossgrabers.sampleconverter.format.sfz.SfzDetectorTask.readFile(SfzDetectorTask.java:87)

at de.mossgrabers.sampleconverter.core.detector.AbstractDetectorTask.detect(AbstractDetectorTask.java:83)

at de.mossgrabers.sampleconverter.core.detector.AbstractDetectorTask.call(AbstractDetectorTask.java:112)

at de.mossgrabers.sampleconverter.core.detector.AbstractDetectorTask.call(AbstractDetectorTask.java:37)

at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)

at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.base/java.lang.Thread.run(Unknown Source)

Caused by: de.mossgrabers.sampleconverter.exception.CompressionNotSupportedException: Unsupported data compression: Extensible

at de.mossgrabers.sampleconverter.file.wav.DataChunk.calculateLength(DataChunk.java:61)

at de.mossgrabers.sampleconverter.core.DefaultSampleMetadata.addMissingInfoFromWaveFile(DefaultSampleMetadata.java:533)

... 12 more

Can't read sample file. Either not a WAV or broken: %1
```

```
C:\Users\simon\Documents\MPC\20211014_keygroup_exp_[ProjectData]\sources\71264_v2_BanjoUkulele_DaveHilowitz_SFZ\Banjo Ukulele [SFZ]\silent>head -n 20 "Banjo Ukulele.sfz"
<group>
seq_length=8
ampeg_release=10
trigger=attack
lovel=0
hivel=79

<region> pitch_keycenter=60 lokey=60 hikey=60 seq_position=1 sample=Samples/BU1_60_C3_p_1.wav
<region> pitch_keycenter=61 lokey=61 hikey=61 seq_position=1 sample=Samples/BU1_61_C#3_p_1.wav
<region> pitch_keycenter=62 lokey=62 hikey=62 seq_position=1 sample=Samples/BU1_62_D3_p_1.wav
<region> pitch_keycenter=63 lokey=63 hikey=63 seq_position=1 sample=Samples/BU1_63_D#3_p_1.wav
<region> pitch_keycenter=64 lokey=64 hikey=64 seq_position=1 sample=Samples/BU1_64_E3_p_1.wav
<region> pitch_keycenter=65 lokey=65 hikey=65 seq_position=1 sample=Samples/BU1_65_F3_p_1.wav
<region> pitch_keycenter=66 lokey=66 hikey=66 seq_position=1 sample=Samples/BU1_66_F#3_p_1.wav
<region> pitch_keycenter=67 lokey=67 hikey=67 seq_position=1 sample=Samples/BU1_67_G3_p_1.wav
<region> pitch_keycenter=68 lokey=68 hikey=68 seq_position=1 sample=Samples/BU1_68_G#3_p_1.wav
<region> pitch_keycenter=69 lokey=69 hikey=69 seq_position=1 sample=Samples/BU1_69_A3_p_1.wav
<region> pitch_keycenter=70 lokey=70 hikey=70 seq_position=1 sample=Samples/BU1_70_A#3_p_1.wav
<region> pitch_keycenter=71 lokey=71 hikey=71 seq_position=1 sample=Samples/BU1_71_B3_p_1.wav
<region> pitch_keycenter=72 lokey=72 hikey=72 seq_position=1 sample=Samples/BU1_72_C4_p_1.wav

C:\Users\simon\Documents\MPC\20211014_keygroup_exp_[ProjectData]\sources\71264_v2_BanjoUkulele_DaveHilowitz_SFZ\Banjo Ukulele [SFZ]\silent>"c:\Program Files (x86)\sox-14.4.2\sox.exe" --info Samples\BU1_60_C3_p_1.wav

Input File     : 'Samples\BU1_60_C3_p_1.wav'
Channels       : 1
Sample Rate    : 8000
Precision      : 32-bit
Duration       : 00:00:03.00 = 24000 samples ~ 225 CDDA sectors
File Size      : 96.1k
Bit Rate       : 256k
Sample Encoding: 32-bit Signed Integer PCM
```
[BU1_60_C3_p_1.zip](https://github.com/git-moss/ConvertWithMoss/files/7358107/BU1_60_C3_p_1.zip)

**Comment by git-moss** [comment]
Do you have some of these files with some meaningful content for testing?

**Comment by mungewell** [comment]
I'm not sure how much more meaningful these are, but here's some 48KHz mono WAVs rendered by sox with different tones in them. _I'm away from my PC with your convertor so unable to confirm whether they cause the same error..._
[tones.zip](https://github.com/git-moss/ConvertWithMoss/files/7385300/tones.zip)

```
C:\Users\swood\Downloads\tones>"c:\Program Files (x86)\sox-14-4-2\sox.exe" --info part_0.wav

Input File     : 'part_0.wav'
Channels       : 1
Sample Rate    : 48000
Precision      : 32-bit
Duration       : 00:00:01.00 = 48000 samples ~ 75 CDDA sectors
File Size      : 192k
Bit Rate       : 1.54M
Sample Encoding: 32-bit Signed Integer PCM
```
