### ISSUE TITLE
Unsupported chunk too short. Whether I use the kontakt, SFZ or EXS converting to DecentSampler

### ISSUE THREAD

**Issue by reaper-sid** [git-moss/ConvertWithMoss#52]
Detected Kontakt Container format (created with Kontakt 5.8.1.43) - Little-Endian.
Unsupported chunk too short. Corrupted file?!
java.lang.IllegalArgumentException: Unsupported chunk too short. Corrupted file?!
at de.mossgrabers.convertwithmoss.file.riff.RIFFChunk.setData(RIFFChunk.java:228)
at de.mossgrabers.convertwithmoss.file.riff.RIFFParser.handleChunks(RIFFParser.java:294)
at de.mossgrabers.convertwithmoss.file.riff.RIFFParser.parseLocalChunk(RIFFParser.java:268)
at de.mossgrabers.convertwithmoss.file.riff.RIFFParser.parseFORM(RIFFParser.java:157)
at de.mossgrabers.convertwithmoss.file.riff.RIFFParser.parseFile(RIFFParser.java:85)
at de.mossgrabers.convertwithmoss.file.riff.RIFFParser.parse(RIFFParser.java:65)
at de.mossgrabers.convertwithmoss.file.wav.WaveFile.read(WaveFile.java:104)
at de.mossgrabers.convertwithmoss.file.wav.WaveFile.<init>(WaveFile.java:78)
at de.mossgrabers.convertwithmoss.format.wav.WavFileSampleData.<init>(WavFileSampleData.java:78)
at de.mossgrabers.convertwithmoss.format.nki.type.kontakt5.Program.createZone(Program.java:396)
at de.mossgrabers.convertwithmoss.format.nki.type.kontakt5.Program.fillInto(Program.java:297)
at de.mossgrabers.convertwithmoss.format.nki.type.kontakt5.Kontakt5Type.convertPrograms(Kontakt5Type.java:195)
at de.mossgrabers.convertwithmoss.format.nki.type.kontakt5.Kontakt5Type.readNIContainer(Kontakt5Type.java:132)
at de.mossgrabers.convertwithmoss.format.nki.type.kontakt5.Kontakt5Type.readNKI(Kontakt5Type.java:97)
at de.mossgrabers.convertwithmoss.format.nki.type.kontakt5.Kontakt5Type.readNKI(Kontakt5Type.java:69)
at de.mossgrabers.convertwithmoss.format.nki.NkiDetectorTask.readFile(NkiDetectorTask.java:58)
at de.mossgrabers.convertwithmoss.core.detector.AbstractDetectorTask.detect(AbstractDetectorTask.java:113)
at de.mossgrabers.convertwithmoss.core.detector.AbstractDetectorTask.call(AbstractDetectorTask.java:143)
at de.mossgrabers.convertwithmoss.core.detector.AbstractDetectorTask.call(AbstractDetectorTask.java:56)
at javafx.concurrent.Task$TaskCallable.call(Task.java:1401)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Finished

**Comment by git-moss** [comment]
Can you send me an example file? Upload to your favorite file hoster and PM me the download link on KVR or post here.
